"""OKF-bundle implementation of ``GraphStore`` — the graph as readable Markdown files (P12).

The knowledge graph is a directory ("bundle") in the Open Knowledge Format pattern
(github.com/google/okf-style: Markdown files + YAML frontmatter, one file per concept, the
file path is the concept's identity). No database server: ``connect()`` loads the whole bundle
into memory (an engagement is O(10^2-10^3) nodes — milliseconds), reads are pure in-memory, and
every mutation writes the affected file(s) back atomically.

Storage model (the Warp Compass OKF profile — docs/plan/phase-12-okf-store.md §4):
  * ``{root}/{type-dir}/{node_id}.md`` — e.g. ``activities/act.check-stock.md``.
  * YAML frontmatter is the machine truth and round-trips ``NodeCard`` exactly:
    ``title`` ⇔ canonical_name, ``keywords`` ⇔ aliases (the few-keyword identifier an LLM uses
    to decide merge-vs-create), ``description``, ``provenance``, and OUTGOING ``edges`` (each
    with type, target id, and its own provenance — vanilla OKF links can't carry provenance).
  * The Markdown body is a generated VIEW, rewritten on every persist: title, description,
    timestamped Facts (from provenance), and two-way wiki-links — outgoing under ``## Links``,
    incoming under ``## Backlinks``. ``add_edge(A→B)`` rewrites BOTH files, so the
    both-sides-see-the-link invariant is structural, never hand-maintained.
  * ``index.md`` at the root and per type dir are regenerated on ``close()``.

Writes are idempotent (merge on id / on the (type, from, to) edge triple, matching the old
Neo4j MERGE semantics) and atomic (tmp file + ``os.replace``), so a Drive-synced bundle never
uploads a half-written node. The brain is the bundle's only writer.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

import yaml
from pydantic import ValidationError

from ..models import ConfidenceStatus, Edge, EdgeType, NodeCard, NodeType, Provenance
from .base import GraphStore

# NodeType -> bundle subdirectory. Kebab-case plural, browsable on GitHub/Drive.
TYPE_DIRS: dict[NodeType, str] = {
    NodeType.ROLE: "roles",
    NodeType.ACTIVITY: "activities",
    NodeType.SYSTEM: "systems",
    NodeType.ARTIFACT: "artifacts",
    NodeType.EVENT: "events",
    NodeType.APPROVAL_POINT: "approval-points",
    NodeType.RULE: "rules",
    NodeType.PROBLEM: "problems",
    NodeType.DESIRE: "desires",
    NodeType.KPI: "kpis",
}

_GENERATED_MARK = (
    "<!-- auto-generated by warp-compass-brain; edit via the pipeline, not by hand -->"
)

# Status severity for the derived display status (ADR #24b: conflicting > confirmed >
# unverified > proposed). Provenance remains the real store; this is the at-a-glance field.
_STATUS_ORDER = [
    ConfidenceStatus.CONFLICTING,
    ConfidenceStatus.CONFIRMED,
    ConfidenceStatus.UNVERIFIED,
    ConfidenceStatus.PROPOSED,
]


def effective_status(provenance: list[Provenance]) -> ConfidenceStatus:
    statuses = {p.status for p in provenance}
    for s in _STATUS_ORDER:
        if s in statuses:
            return s
    return ConfidenceStatus.PROPOSED


def _prov_to_yaml(p: Provenance) -> dict:
    return {
        "said_by": p.said_by,
        "session_id": p.session_id,
        "confidence": p.confidence,
        "status": p.status.value,
        "ts": p.ts,
    }


class OkfGraphStore(GraphStore):
    """Concrete GraphStore over an OKF Markdown bundle on disk."""

    def __init__(self, root: str | Path) -> None:
        self._root = Path(root)
        self._nodes: dict[str, NodeCard] = {}
        self._edges: list[Edge] = []
        self._connected = False
        self._dirty = False  # anything written since connect? (drives index regeneration)

    # --- lifecycle ---

    def connect(self) -> None:
        self._root.mkdir(parents=True, exist_ok=True)
        self._nodes, self._edges = self._load_bundle()
        self._connected = True
        self._dirty = False

    def close(self) -> None:
        if self._connected and self._dirty:
            self._write_indexes()
        self._connected = False

    # --- nodes ---

    def upsert_node(self, card: NodeCard) -> None:
        self._check_connected()
        prior = self._nodes.get(card.id)
        self._nodes[card.id] = card.model_copy(deep=True)
        self._persist_node(card.id)
        # A renamed node changes how neighbours render its wiki-link line.
        if prior is not None and prior.canonical_name != card.canonical_name:
            for other in self._linked_node_ids(card.id):
                self._persist_node(other)

    def get_node(self, node_id: str) -> NodeCard | None:
        self._check_connected()
        card = self._nodes.get(node_id)
        return card.model_copy(deep=True) if card else None

    def find_by_alias(self, name: str, node_type: str | None = None) -> list[NodeCard]:
        self._check_connected()
        low = name.lower()
        out: list[NodeCard] = []
        for card in self._nodes.values():
            if node_type and card.type.value != node_type:
                continue
            names = {card.canonical_name.lower(), *(a.lower() for a in card.aliases)}
            if low in names:
                out.append(card.model_copy(deep=True))
        return sorted(out, key=lambda c: c.id)

    def add_provenance(self, node_id: str, provenance: Provenance) -> None:
        self._check_connected()
        card = self._nodes.get(node_id)
        if card is None:
            raise KeyError(f"no node {node_id!r}")
        card.provenance.append(provenance)
        self._persist_node(node_id)

    def set_status(self, node_id: str, status: ConfidenceStatus) -> None:
        self._check_connected()
        card = self._nodes.get(node_id)
        if card is None:
            return
        if card.provenance:
            card.provenance[-1].status = status
        self._persist_node(node_id)

    # --- edges ---

    def add_edge(self, edge: Edge) -> None:
        self._check_connected()
        if edge.from_id not in self._nodes or edge.to_id not in self._nodes:
            # Neo4j's MATCH..MERGE silently no-opped on a missing endpoint; keep that contract.
            return
        for i, e in enumerate(self._edges):
            if e.type == edge.type and e.from_id == edge.from_id and e.to_id == edge.to_id:
                self._edges[i] = edge.model_copy(deep=True)  # MERGE: overwrite provenance
                break
        else:
            self._edges.append(edge.model_copy(deep=True))
        # Two-way link sync: the giver's Links section AND the receiver's Backlinks section.
        self._persist_node(edge.from_id)
        self._persist_node(edge.to_id)

    def neighbors(self, node_id: str, edge_type: EdgeType | None = None) -> list[NodeCard]:
        self._check_connected()
        out: list[NodeCard] = []
        for e in self._edges:
            if e.from_id != node_id or (edge_type is not None and e.type != edge_type):
                continue
            tgt = self._nodes.get(e.to_id)
            if tgt is not None:
                out.append(tgt.model_copy(deep=True))
        return out

    # --- bulk reads ---

    def nodes_by_type(self, node_type: str) -> list[NodeCard]:
        self._check_connected()
        if node_type not in {t.value for t in NodeType}:
            raise ValueError(f"unknown node type: {node_type!r}")
        return sorted(
            (c.model_copy(deep=True) for c in self._nodes.values() if c.type.value == node_type),
            key=lambda c: c.id,
        )

    def edges(self, edge_type: EdgeType | None = None) -> list[Edge]:
        self._check_connected()
        return [
            e.model_copy(deep=True)
            for e in self._edges
            if edge_type is None or e.type == edge_type
        ]

    # --- loading ---

    def _load_bundle(self) -> tuple[dict[str, NodeCard], list[Edge]]:
        nodes: dict[str, NodeCard] = {}
        edges: list[Edge] = []
        for node_type, dirname in TYPE_DIRS.items():
            d = self._root / dirname
            if not d.is_dir():
                continue
            for path in sorted(d.glob("*.md")):
                if path.name == "index.md":
                    continue
                parsed = self._parse_node_file(path, node_type)
                if parsed is None:
                    continue
                card, node_edges = parsed
                if card.id in nodes:
                    _warn(f"duplicate node id {card.id!r} at {path}; keeping the first")
                    continue
                nodes[card.id] = card
                edges.extend(node_edges)
        # Drop edges whose endpoints didn't load (tolerant, like FolderBus reads).
        loaded = set(nodes)
        kept: list[Edge] = []
        for e in edges:
            if e.from_id in loaded and e.to_id in loaded:
                kept.append(e)
            else:
                _warn(f"dropping edge {e.type.value} {e.from_id}->{e.to_id}: missing endpoint")
        return nodes, kept

    def _parse_node_file(
        self, path: Path, expected_type: NodeType
    ) -> tuple[NodeCard, list[Edge]] | None:
        try:
            text = path.read_text(encoding="utf-8")
            fm = _frontmatter(text)
            if fm is None:
                _warn(f"skipping {path}: no YAML frontmatter")
                return None
            card = NodeCard(
                id=fm["id"],
                type=NodeType(fm.get("type", expected_type.value)),
                canonical_name=fm.get("title") or fm["id"],
                aliases=list(fm.get("keywords") or []),
                description=fm.get("description") or "",
                category_codes=list(fm.get("category_codes") or []),
                key_attributes=dict(fm.get("key_attributes") or {}),
                provenance=[Provenance.model_validate(p) for p in (fm.get("provenance") or [])],
            )
            node_edges = [
                Edge(
                    type=EdgeType(e["type"]),
                    from_id=card.id,
                    to_id=e["to"],
                    provenance=[
                        Provenance.model_validate(p) for p in (e.get("provenance") or [])
                    ],
                )
                for e in (fm.get("edges") or [])
            ]
            if card.type is not expected_type:
                _warn(f"{path}: type {card.type.value} filed under {expected_type.value} dir")
            return card, node_edges
        except (KeyError, ValueError, ValidationError, yaml.YAMLError, OSError) as exc:
            _warn(f"skipping unreadable node file {path}: {exc}")
            return None

    # --- persistence ---

    def _node_path(self, card: NodeCard) -> Path:
        return self._root / TYPE_DIRS[card.type] / f"{card.id}.md"

    def _persist_node(self, node_id: str) -> None:
        card = self._nodes[node_id]
        self._atomic_write(self._node_path(card), self._render_node(card))
        self._dirty = True

    def _out_edges(self, node_id: str) -> list[Edge]:
        return sorted(
            (e for e in self._edges if e.from_id == node_id),
            key=lambda e: (e.type.value, e.to_id),
        )

    def _in_edges(self, node_id: str) -> list[Edge]:
        return sorted(
            (e for e in self._edges if e.to_id == node_id),
            key=lambda e: (e.type.value, e.from_id),
        )

    def _linked_node_ids(self, node_id: str) -> set[str]:
        out: set[str] = set()
        for e in self._edges:
            if e.from_id == node_id:
                out.add(e.to_id)
            elif e.to_id == node_id:
                out.add(e.from_id)
        return out

    def _render_node(self, card: NodeCard) -> str:
        status = effective_status(card.provenance)
        latest_ts = max((p.ts for p in card.provenance), default=None)
        fm: dict = {
            "type": card.type.value,
            "id": card.id,
            "title": card.canonical_name,
            "keywords": list(card.aliases),
            "description": card.description,
            "status": status.value,
            "category_codes": list(card.category_codes),
            "key_attributes": dict(card.key_attributes),
            "provenance": [_prov_to_yaml(p) for p in card.provenance],
            "edges": [
                {
                    "type": e.type.value,
                    "to": e.to_id,
                    "provenance": [_prov_to_yaml(p) for p in e.provenance],
                }
                for e in self._out_edges(card.id)
            ],
        }
        if latest_ts:
            fm["timestamp"] = latest_ts

        lines: list[str] = [f"# {card.canonical_name}", ""]
        meta = f"> **{card.type.value}** `{card.id}` · status **{status.value}**"
        if card.aliases:
            meta += f" · keywords: {', '.join(card.aliases)}"
        lines += [meta, ""]
        if card.description:
            lines += [card.description, ""]
        if card.key_attributes:
            lines.append("## Attributes")
            for k in sorted(card.key_attributes):
                lines.append(f"- **{k}:** {card.key_attributes[k]}")
            lines.append("")
        if card.provenance:
            lines.append("## Facts")
            for p in card.provenance:
                day = p.ts[:10] if len(p.ts) >= 10 else p.ts
                lines.append(
                    f"- {day} — {p.said_by} (session {p.session_id}, "
                    f"confidence {p.confidence:g}, {p.status.value})"
                )
            lines.append("")
        outgoing = self._out_edges(card.id)
        if outgoing:
            lines.append("## Links")
            for e in outgoing:
                tgt = self._nodes.get(e.to_id)
                name = f" — {tgt.canonical_name}" if tgt else ""
                lines.append(f"- {e.type.value} → [[{e.to_id}]]{name}")
            lines.append("")
        incoming = self._in_edges(card.id)
        if incoming:
            lines.append("## Backlinks")
            for e in incoming:
                src = self._nodes.get(e.from_id)
                name = f" ({src.canonical_name})" if src else ""
                lines.append(f"- [[{e.from_id}]]{name} — {e.type.value}")
            lines.append("")
        lines.append(_GENERATED_MARK)

        front = yaml.safe_dump(fm, sort_keys=False, allow_unicode=True, width=100)
        return f"---\n{front}---\n\n" + "\n".join(lines) + "\n"

    # --- indexes (progressive disclosure) ---

    def _write_indexes(self) -> None:
        by_type: dict[NodeType, list[NodeCard]] = {t: [] for t in NodeType}
        for card in self._nodes.values():
            by_type[card.type].append(card)

        root_lines = [
            "# Warp Compass — knowledge graph (OKF bundle)",
            "",
            "One Markdown file per concept; YAML frontmatter is the machine truth; the body is",
            "a generated human/agent view with two-way `[[wiki-links]]`. Written by the brain",
            "pipeline — do not edit by hand.",
            "",
            "| Type | Count | Folder |",
            "|---|---|---|",
        ]
        for t in NodeType:
            cards = sorted(by_type[t], key=lambda c: c.id)
            d_name = TYPE_DIRS[t]
            root_lines.append(f"| {t.value} | {len(cards)} | [{d_name}/]({d_name}/index.md) |")
            if not cards:
                continue
            dir_lines = [f"# {t.value} nodes", ""]
            for c in cards:
                kw = f" · keywords: {', '.join(c.aliases)}" if c.aliases else ""
                desc = f" — {c.description}" if c.description else ""
                dir_lines.append(
                    f"- [[{c.id}]] **{c.canonical_name}**"
                    f" ({effective_status(c.provenance).value}){kw}{desc}"
                )
            dir_lines += ["", _GENERATED_MARK]
            d = self._root / TYPE_DIRS[t]
            d.mkdir(parents=True, exist_ok=True)
            self._atomic_write(d / "index.md", "\n".join(dir_lines) + "\n")
        root_lines += ["", _GENERATED_MARK]
        self._atomic_write(self._root / "index.md", "\n".join(root_lines) + "\n")

    # --- internals ---

    def _check_connected(self) -> None:
        if not self._connected:
            raise RuntimeError("GraphStore not connected; call connect() first.")

    def _atomic_write(self, path: Path, text: str) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp = path.with_suffix(path.suffix + ".tmp")
        tmp.write_text(text, encoding="utf-8", newline="\n")
        os.replace(tmp, path)


def _frontmatter(text: str) -> dict | None:
    """Parse the leading ``--- ... ---`` YAML block, or None if the file has none."""
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end == -1:
        return None
    data = yaml.safe_load(text[3:end])
    return data if isinstance(data, dict) else None


def _warn(msg: str) -> None:
    print(f"[okf-store] WARNING: {msg}", file=sys.stderr)
